### DISCUSSION TITLE
Current outage due to SSL certification issue

### DISCUSSION THREAD

**Discussion by Geod24** [dlang/dmd#12123] [CI]
Hi everyone,
As you might have noticed, the CI is currently completely broken due to some SSL issues.

## What's happening

*On some systems*, downloading `https://dlang.org/install.sh` fails:
```shell
$ curl https://dlang.org/install.sh
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

On some systems, it succeeds.

## Why it's happening

My understanding is that the current configuration of dlang.org is incorrect, inasmuch as it does not server the *intermediate certificate(s)*, but only its own certificate (and an extra certificate for a co-hosted website). This is backed by the error message (unable to verify *first* certificate) and SSLLabs: https://www.ssllabs.com/ssltest/analyze.html?d=dlang.org

<img width="957" alt="Screen Shot 2021-01-11 at 13 36 26" src="https://user-images.githubusercontent.com/2180215/104147532-11389f00-5412-11eb-8d85-2bc7c920b645.png">

## How to fix it

The server needs to send the full path to the root certificate. Alternatively, tools might be able to work around it by downloading the missing intermediate certificate (I'll explore this in `setup-dlang`).

## When will it be fixed

We don't know yet, as only one person can fix this, but ASAP.

**Comment by Geod24** [comment]
The Github action has been hotfixed, but the problem persists with other CIs: https://github.com/dlang-community/setup-dlang/releases/tag/v1.0.4

**Comment by ibuclaw** [comment]
Thanks!  Maybe we should have a few more accounts on the downloads server to give us some redundancy of people available to act when these sorts of things happen?

**Reply by Geod24** [reply]
I think it would be good, I'll bring it up at the next foundation meeting.

**Comment by Geod24** [comment]
Everything should be back to normal now, thanks to Jan.

**Comment by p0nce** [comment]
Still getting this on Travis CI, I wonder what to do?

**Reply by Geod24** [reply]
Works for me (the certificate). Is the `install.sh` on Travis CI outdated ?

**Reply by p0nce** [reply]
~~It is the download of install.sh that fails.~~ not sure

My CI log:
```
$ git clone --depth=50 --branch=v1.6.1 https://github.com/AuburnSounds/intel-intrinsics.git AuburnSounds/intel-intrinsics
D support for Travis-CI is community maintained.
Please make sure to ping @MartinNowak and @wilzbach when filing issues under https://travis-ci.community/c/languages/d.
DMD-related issues: https://issues.dlang.org
LDC-related issues: https://github.com/ldc-developers/ldc/issues
GDC-related issues: https://bugzilla.gdcproject.org
DUB-related issues: https://github.com/dlang/dub/issues
Installing compiler and dub
$ CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
$ __mirrors=(
    "https://dlang.org/install.sh"
    "https://nightlies.dlang.org/install.sh"
    "https://github.com/dlang/installer/raw/stable/script/install.sh"
  )
  for i in {0..4}; do
    for mirror in "${__mirrors[@]}" ; do
      if curl -fsSL -A "$CURL_USER_AGENT" --connect-timeout 5 --speed-time 30 --speed-limit 1024 "$mirror" -O ; then
        break 2
      fi
    done
    sleep $((1 << i))
  done
  unset __mirrors
  
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
curl: (28) Connection timed out after 5001 milliseconds
4.09s$ source "$(CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh dmd-2.097.0 --activate)"

// more of the same
```

**Reply by Geod24** [reply]
> https://nightlies.dlang.org/install.sh

This one is definitely a dead link.

**Reply by p0nce** [reply]
That means the travis.ci D integration is broken for everyone? I'm not doing anything special.

**Reply by Geod24** [reply]
I would CC @MartinNowak and @wilzbach here.

**Reply by PetarKirov** [reply]
I think the problem is with Travis CI's curl, as this works for me:

```bash
CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
curl -fsSL -A "$CURL_USER_AGENT" --connect-timeout 5 --speed-time 30 --speed-limit 1024 "https://dlang.org/install.sh" -O
```

**Reply by PetarKirov** [reply]
@p0nce the work around would be to manually run the steps in this script in order to download the `install.sh` script in `before_install`:
https://github.com/travis-ci/travis-build/blob/5f10098154313ca99ed72dbf75c7bdf670708f2b/lib/travis/build/script/d.rb

If that doesn't work, you could try asking the TravisCI team here: https://travis-ci.community/ as essentially `d.rb` is their responsibility, even though our community contributed it.

**Reply by p0nce** [reply]
Looking for a fix not a workaround. Travis still gives free credits for open-source and is one of the only free CI to have arm64

**Reply by PetarKirov** [reply]
> Looking for a fix not a workaround.

Agreed, but based on the available information I still think the issue is with TravisCI, so I'm not sure what we can do to fix it, other than suggest you find a way to download `dlang.org/install.sh` manually or use pre-built docker images.

> Travis still gives free credits for open-source and is one of the only free CI to have arm64

[cirrus-ci](https://cirrus-ci.org) also supports Linux arm64 (and also FreeBSD) and provides free credits for open-source.

**Reply by PetarKirov** [reply]
I ran into the Travis CI SSL issue recently myself. From what I can see, I still think that the problem is on their side, as of several jobs in the same build some pass without issues and some fail:

* https://app.travis-ci.com/github/symmetryinvestments/influx-d/jobs/548517525
* https://app.travis-ci.com/github/symmetryinvestments/influx-d/jobs/548517529

**Comment by p0nce** [comment]
The .travis.yml file:

```yml
language: d

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then sudo apt-get install -y gcc-multilib ; fi

arch:
  - amd64
  - arm64

os:
  - linux

d:
 - ldc-1.26.0
 - ldc-1.24.0
 - dmd-beta
 - dmd-2.097.0
 - dmd-2.094.2

matrix:
  allow_failures:
   - d: dmd-beta      # DMD on arm64 not supported
     arch: arm64
   - d: dmd-2.097.0
     arch: arm64
   - d: dmd-2.094.2
     arch: arm64

# Note: run 64-bit tests if (arch == amd64) || (compiler is LDC)
# Note: run 32-bit tests on Linux x86 only
# Note: need '' escaping because of fricking YAML
script:
  - 'if [[ "${DC: -4}" == "ldc2" || "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} ; fi'
  - 'if [[ "${DC: -4}" == "ldc2" || "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-release --compiler=${DC} ; fi'
  - 'if [[ "${DC: -4}" == "ldc2" || "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-inst --compiler=${DC} ; fi'
  - 'if [[ "${DC: -4}" == "ldc2" || "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-release-inst --compiler=${DC} ; fi'
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-release --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-inst --compiler=${DC} -a x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then dub test -b unittest-release-inst --compiler=${DC} -a x86 ; fi
```
